#! /bin/bash

# Usage of the works is permitted provided that this
# instrument is retained with the works, so that any entity
# that uses the works is notified of this instrument.
#
# DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.

export build_name=ddebug
export build_options=-D_DEBUG
"${0%/*}"/mak.sh "$@"

export build_name=ddebugx
export build_options="-D_DEBUG -D_PM"
"${0%/*}"/mak.sh "$@"

